### ISSUE TITLE
Bug when both die

### ISSUE THREAD

**Issue by Jgorenburg** [bear-socks/BearFun#1]
When both characters dash into each other, they both die (intended) but don't come back (unintended). As far as I can tell, the gameState.resetPlayer1 ticks down to 1 but doesn't go to 0 for some reason.

**Comment by htaussig** [comment]
yeah line 272 and 252 get called when the players aren't actually alive which means resetPlayer1 must have a value of -1?

**Comment by htaussig** [comment]
Also, I think the collider may get messed up at line 182? is that being destroyed along with player1? probably not? Is it possible that we are recreating the collider unnecessarily?
